
# After a PR to main, build the package and upload as release
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build and Release
permissions: write-all
jobs:
    upload-release:
        runs-on: ubuntu-latest
        env:
            PACKAGE_NAME: asgs.geocode
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup R
                uses: r-lib/actions/setup-r@v2
                with:
                    use-public-rspm: true
            -   name: Setup R deps
                uses: r-lib/actions/setup-r-dependencies@v2
                with:
                    extra-packages: any::rcmdcheck
                    needs: check
            -   name: Install package
                shell: Rscript {0}
                run: |
                    pak::pkg_install(pkg = ".")
            -   name: Get news
                shell: Rscript {0}
                run: |
                    vers <- packageVersion("${{ env.PACKAGE_NAME }}")
                    out <- utils::news(Version == vers, package = "${{ env.PACKAGE_NAME }}")
                    writeLines(out$HTML, con = "changes.md")
            -   name: Get package version
                run: |
                    echo "version=$(Rscript -e cat\(as.character\(packageVersion\(\"${{ env.PACKAGE_NAME }}\"\)\)\))" >> "$GITHUB_ENV"
            -   name: Build R package
                shell: Rscript {0}
                run: |
                    pkgbuild::build(path = ".", vignettes = TRUE)
            -   name: Upload Release
                uses: ncipollo/release-action@v1.12.0
                with:
                    artifacts: "${{ env.PACKAGE_NAME }}_${{ env.version }}.tar.gz"
                    name: "${{ env.version }}"
                    bodyFile: "changes.md"
                    tag: "${{ env.version }}"
