
# After a PR to main, build the package and upload as release
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build and Release
permissions: write-all
jobs:
    upload-release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup R
                uses: r-lib/actions/setup-r@v2
                with:
                    use-public-rspm: true
            -   name: Setup R deps
                uses: r-lib/actions/setup-r-dependencies@v2
                with:
                    extra-packages: any::rcmdcheck
                    needs: check
            -   name: Install devtools and package
                shell: Rscript {0}
                run: |
                    pak::pkg_install(pkg = c("devtools", "."))
            -   name: Get news
                shell: Rscript {0}
                run: |
                    vers <- packageVersion("asgs.geocode")
                    out <- utils::news(Version == vers, package = "asgs.geocode")
                    writeLines(out$Text, con = "changes.md")
            -   name: Get package version
                run: |
                    echo "version=$(Rscript -e cat\(as.character\(packageVersion\(\"asgs.geocode\"\)\)\))" >> "$GITHUB_ENV"
            -   name: Build R package
                shell: Rscript {0}
                run: |
                    devtools::build(vignettes = TRUE)
            -   name: Upload Release
                uses: ncipollo/release-action@v1.12.0
                with:
                    artifacts: "asgs.geocode_${{ env.version }}.tar.gz"
                    name: "${{ env.version }}"
                    bodyFile: "changes.md"
                    tag: "${{ env.version }}"
